"""Assemble one Z1 program: drill everything, change tool, cut the outline.

One file with an in-program M6 rather than two files, so XY origin is set once
and Z0 carries across the change via the new tool's TLO. Ordering is not
cosmetic: the outline cut goes LAST because it is the op that frees the part.
Anything still to be done to a board that is no longer held down is a mistake.
"""
import os

import pcbnew

from . import gcode, geometry, holes, ops, verify

BREAKTHROUGH_MM = 0.2   # go past the far face; a sacrificial layer takes it


class Options(object):
    def __init__(self, outfile,
                 do_drill=True, do_cut=True, include_vias=False,
                 depth=None, rpm=13000,
                 drill_tool=1, drill_dia=0.7, drill_desc=None,
                 drill_feed=60.0, drill_plunge=30.0, helix_pitch=0.15,
                 cut_tool=2, cut_dia=1.2, cut_desc=None,
                 cut_feed=150.0, cut_plunge=40.0, cut_stepdown=0.4,
                 tab_count=4, tab_width=1.0, tab_z=-1.0,
                 pause_for_pins=True):
        for k, v in list(locals().items()):
            if k != "self":
                setattr(self, k, v)
        # The tool description is what the M6 prompt shows the operator, so keep
        # it honest about the diameter actually being used rather than a label
        # left over from a different bit.
        self.drill_desc = drill_desc or "%.2fmm bit" % drill_dia
        self.cut_desc = cut_desc or "%.2fmm bit" % cut_dia


def default_depth(board):
    """Board thickness plus a breakthrough allowance."""
    try:
        t = pcbnew.ToMM(board.GetDesignSettings().GetBoardThickness())
    except Exception:
        t = 1.6
    return round((t if t > 0 else 1.6) + BREAKTHROUGH_MM, 2)


def build(board, opt, log=None):
    """Return the g-code text. Raises rather than emitting doubtful output."""
    log = log or (lambda m: None)
    if not (opt.do_drill or opt.do_cut):
        raise gcode.GcodeError("Nothing selected: pick drilling, cutting, or both.")
    depth = opt.depth if opt.depth else default_depth(board)
    if opt.do_cut and opt.tab_z <= -depth:
        raise gcode.GcodeError(
            "Tab height %.2fmm is at or below the %.2fmm cut depth, so the tabs "
            "would be cut through and the part would come loose mid-cut."
            % (opt.tab_z, depth))

    reg, inside, all_holes = [], [], []
    if opt.do_drill:
        all_holes = holes.collect(board, include_vias=opt.include_vias)
        if not all_holes:
            raise gcode.GcodeError(
                "No drillable holes found. This board has no through-hole pads "
                "(vias are excluded unless you tick 'include vias').")
        holes.check_tool(all_holes, opt.drill_dia)
        reg, inside = holes.partition(board, all_holes)

    paths, dropped = ([], 0)
    if opt.do_cut:
        paths, dropped = geometry.cut_paths(board, opt.cut_dia)
        if dropped:
            log("WARNING: %d internal cutout(s) are too small for the %.2fmm "
                "cutter and are NOT machined." % (dropped, opt.cut_dia))

    w = gcode.Writer(rpm=opt.rpm)
    notes = [
        "Generated by kicad-gcode-plugin from %s"
        % os.path.basename(board.GetFileName() or "(unsaved)"),
        "Origin = KiCad drill/place (aux) origin. Set XY once; do not move it.",
        "Cut depth %.2fmm -- USE A SACRIFICIAL LAYER." % depth,
    ]
    if opt.do_drill:
        notes.append("T%d = %s : %d hole(s)"
                     % (opt.drill_tool, opt.drill_desc, len(all_holes)))
    if opt.do_cut:
        notes.append("T%d = %s : outline, %d tab(s) of %.2fmm at Z%.2f"
                     % (opt.cut_tool, opt.cut_desc, opt.tab_count,
                        opt.tab_width, opt.tab_z))
    notes.append("SETUP: install the first tool, Change tool to register it,")
    notes.append("  set XY origin, Auto Z Probe ON, then Run.")
    w.header("Makera Z1 -- drill + outline cutout", notes)

    first = True
    if opt.do_drill:
        w.toolchange(opt.drill_tool, opt.drill_desc, first=True)
        first = False
        if reg:
            w.comment("-- registration holes first, so the blank can be pinned --")
            ops.drill_all(w, reg, opt.drill_dia, depth, opt.drill_feed,
                          opt.drill_plunge, opt.helix_pitch)
            log("Registration holes (outside the outline): %d" % len(reg))
            if opt.pause_for_pins and inside:
                w.pause("Fit the dowel pins, then press play")
        if inside:
            w.comment("-- through-holes --")
            ops.drill_all(w, inside, opt.drill_dia, depth, opt.drill_feed,
                          opt.drill_plunge, opt.helix_pitch)
        for dia, group in holes.by_diameter(all_holes):
            log("  %.2fmm x %d" % (dia, len(group)))

    if opt.do_cut:
        w.toolchange(opt.cut_tool, opt.cut_desc, first=first)
        w.comment("-- outline cutout (LAST: this frees the part) --")
        ops.cut_outline(w, paths, depth, opt.cut_stepdown, opt.cut_feed,
                        opt.cut_plunge, opt.tab_count, opt.tab_width, opt.tab_z)
        log("Outline: %d path(s), %.1fmm total"
            % (len(paths), sum(geometry.perimeter(p) for p in paths)))

    w.footer()
    text = w.text()
    stats = verify.check(text, depth)
    log("Verified: %d lines, deepest Z %.3fmm." % (stats["lines"], stats["zmin"]))
    return text


def write(board, opt, log=None):
    text = build(board, opt, log=log)
    with open(opt.outfile, "w") as fh:
        fh.write(text)
    return opt.outfile
